import 'package:flutter/material.dart';

// This file is auto-generated by flutter_gen
import '../assets/colors.gen.dart';

class AppTheme {
  static ThemeData get lightTheme {
    return ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: ColorName.primary,
        primary: ColorName.primary,
        secondary: ColorName.accent,
        background: ColorName.background,
        error: ColorName.error,
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: ColorName.primary,
        foregroundColor: ColorName.textInverse,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: ColorName.textPrimary),
        bodyMedium: TextStyle(color: ColorName.textSecondary),
      ),
    );
  }

  static ThemeData get darkTheme {
    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.dark,
      colorScheme: ColorScheme.fromSeed(
        brightness: Brightness.dark,
        seedColor: ColorName.primaryDark,
        primary: ColorName.primaryDark,
        secondary: ColorName.accent,
        background: ColorName.backgroundDark,
        error: ColorName.error,
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: ColorName.primaryDark,
        foregroundColor: ColorName.textInverse,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: ColorName.textInverse),
        bodyMedium: TextStyle(color: ColorName.textSecondary),
      ),
    );
  }
}
